name: Build

on:
  push:
    branches: 
      - actions
  pull_request:
    branches: 
      - actions

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Commit Information
      id: commit
      run: |
        echo "::set-output name=commit_id::commit-$(git rev-parse --short HEAD)"
        echo "::set-output name=commit_message::$(git log -1 --pretty=%B)"W
    - name: Prepare for Build
      run: |
        git clone --depth=1 --branch=patch --single-branch "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" Patch
        Copy-Item Patch/FontInfo.json Fonts/FontInfo.json -Force
    - name: Create Font
      continue-on-error: true
      run: |
        Bin/ATSFChsPatchCreate.exe
    - name: Deploy to GitHub
      run: |
        Copy-Item Fonts/FontInfo.json Patch/FontInfo.json -Force
        cd Patch/
        git add -A
        git -c user.name=GitHub -c user.email=noreply@github.com commit -m "${{ steps.commit.outputs.commit_message }}" -m "Based on commit ${{ steps.commit.outputs.commit_id }}, from GitHub Actions build ${{ github.run_number }}"
        git push
        cd ../
    - uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        name: Patch
        path: |
          Patch/
          !Patch/.git/
          !Patch/.gitignore
          !Patch/FontInfo.json